# -*- coding: utf-8 -*-
"""analisis_pro_usuario.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/129H3FsSxsbV-dV4Ztdy6bzjtCiPpT2SV

**Autora:** Suny Brunoldi

**Información utilizada:** [Superintendencia de Bancos](https://sb.gob.do/transparencia/datos-abiertos/usuarios-atendidos-por-la-oficina-de-servicios-y-proteccion-al-usuario-prousuario/)

# **Análisis y rendimiento de canales de ProUsuario**
ProUsuario es una entidad que busca garantizar que cada persona reciba un trato justo, transparente y seguro al interactuar con productos y servicios financieros, por esto, el servicio al cliente es uno de los pilares más importantes de esta empresa, puesto que su objetivo principal es satisfacer las necesidades de los clientes, generándoles la confianza sufienciente para crear lealtad con el consumidor.

[Fuente](https://prousuario.gob.do/nosotros/qui%C3%A9nes-somos/)

# Objetivos
*   Analizar el redimiento de los diferentes canales de atención para los clientes y visualizar la evolución de estas herramientas, promoviendo la mejora continua y optimización del servicio al consumidor.

*   Identificar oportunidades de digitalización y mejorar la asignación de recursos operativos.

**Importación de archivos**
"""

from google.colab import drive
from google.colab import files
drive.mount('/content/drive')

"""**Importación de librería de lectura de archivos y lectura del archivo a utilizar**"""

import pandas as pd
df_usuario = pd.read_csv("/content/drive/MyDrive/Portafolio_data/Estadísiticas_ProUsuario/estadísticas-de-usuarios-atendidos-por-prousuario-2019-2026 (1).csv")

df_usuario.info()

df_usuario.head()

"""# **Análisis explotario (EDA)**


*   Análisis de valores faltantes
*   Análisis de valores duplicados
*   Análisis de expresiones
*   Análisis de variables numéricas







"""

df_usuario.columns

df_usuario = df_usuario.rename(columns = {"Correo Electrónico" : "Correo_electrónico" ,
                                          "Vía Telefónica": "Vía_telefónica",
                                          "Atención Virtual": "Atención_virtual",
                                          "Redes Sociales": "Redes_sociales",
                                          "Consultas Página Web": "Consultas_página_web",
                                          "ChatBot WhatsApp": "ChatBot_Whatsapp",
                                          "ChatBot Web": "ChatBot_web"})

df_usuario.isnull().sum()

df_usuario.duplicated().sum()

df_usuario.drop('Año', axis=1).describe()

"""# **Visualización del redimiento de los usuarios lo largo del tiempo**

"""

import seaborn as sns
import matplotlib.pyplot as plt
sns.set_theme(style="darkgrid")
sns.barplot(
    data=df_usuario,
    x="Año",
    y="Total",
    hue="Año",
    legend=False,
    palette="viridis"
)
plt.title("Total de usuarios atendidos por año")
plt.xlabel("Año")
plt.ylabel("Total de usuarios atendidos")
plt.tight_layout()
plt.show()

"""**¿Cómo ha evolucionado la atención al cliente desde 2019 al 2026?**

La atención al cliente ha evolucionado de forma exponencial. Lo que significa que, a medida que los años han ido avanzando, la cantidad de usuarios atendidos también estuvo ascendiendo. Únicamente en 2024 hubo una ligera variación, pero después sigue representando el mismo patrón.

# **Visualización de los canales más utilizados**
"""

canales = [
    "Presencial",
    "Correo_electrónico",
    "Vía_telefónica",
    "Chat",
    "Whatsapp",
    "Atención_virtual",
    "Redes_sociales",
    "IVR",
    "Consultas_página_web",
    "ChatBot_Whatsapp",
    "ChatBot_web"
]

ranking_canales = (
    df_usuario[canales]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

ranking_canales.columns = ["Canal", "Usuarios"]
plt.figure(figsize=(12,7))

sns.barplot(
    data=ranking_canales,
    x="Usuarios",
    y="Canal",
    hue="Canal",
    palette="viridis",
    legend=False
)

plt.title(
    "Canales de atención más utilizados",
    fontsize=16,
    fontweight="bold"
)

plt.xlabel("Cantidad de usuarios")
plt.ylabel("Canal")

plt.tight_layout()
plt.show()

"""**Rendimiento de las vías de comunicación: ¿cuáles canales poseen un mayor uso y crecimiento a lo largo del tiempo?**

El canal más utilizado es el ChatBot Web. Este medio de atención funciona gracias a su habilidad para responder de forma inmediata y personalizar el servicio, aprovechando los algoritmos del procesamiento del lenguaje natural (NLP) para interpretar y humanizar las conversaciones con el cliente.

El segundo canal más utilizado es la vía telefónica. Este medio ofrece una conexión más personal y una comunicación instantánea con las preocupaciones del cliente. Además, genera buenas primeras impresiones para retener usuarios.

# **Insights y recomendaciones**


*   Los canales automáticos absorben más del 60% del tráfico total. Esto indica que la estrategia de autoservicio está funcionando y los usuarios prefieren soluciones inmediatas. Así que, ProUsuario procurar mantener sus algoritmos de aprendizaje automático fortalecidos para seguir adaptando el servicio a las nuevas tendencias y necesidades.

*   Aunque la asistencia virtual es muy óptima, no pueden dejar de lado la asistencia presencial y telefónica, puesto que permite un entendimiento más profundo del sentimiento del cliente y de problemas más complejos. Por esto, ProUsuario debe tener un personal altamente capacitado para resolver problemas que la automatización no pudo solucionar.
"""